spring:
  profiles: dev
    
 #redis
  redis: 
    host: 127.0.0.1
    port: 6379
    database: 0
    password: 
    timeout: 10000
    jedis: 
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
      
      
server: 
  port: 8040
eureka: 
  client: 
    service-url:
      defaultZone: http://user:password123@localhost:8761/register-service/eureka/
  instance:
    prefer-ip-address: true
    
zuul:
  routes:
    test: 
      path: /test/**
      service-id: test