spring: 
  profiles: prod
  
 #redis
  redis: 
    host: localhost
    password: 
    port: 6379
    pool: 
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
      
server:
  port: 8040
eureka:
  client:
    service-url:
      defaultZone: http://user:password123@192.168.40.132:8761/register-service/eureka/
  instance:
    prefer-ip-address: true