logging:
 config: classpath:log4j2.yml
 

    
spring:
  banner:
   location: classpath:config/buddha.txt
  application: 
    name: cndatacom-cloud-zuul
    
  profiles:
    active: dev

security: 
  config:
    expire-time: 1800000
    hashAlgorithmName: md5
    salt: 2017
    hashIterations: 1
    isOpenAuthUser: OPEN
    
simons: 
  user: 
    user-expire-time: 10800

uri: 
 white:
  - /user/region/account_login
  - /sys/user/check_account
  - /sys/user/register
  - /sys/check/get_check_code
  - /sys/check/login_phone_check
  - /task/data_check_result/get_check_result
  - /sys/check/keep_login